### ISSUE TITLE
use statement in shell

### ISSUE THREAD

**Issue by Aletz-Arce** [wp-cli/shell-command#19]
Hi 
When i try, to use 'use statement', shell exited with not message error.
I'm use themosis framework to develop a plugin. I'm try to prototype very basic code;

Thanks

**Comment by danielbachhuber** [comment]
Hi @Aletz-Arce,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
