### ISSUE TITLE
What is Boris?

### ISSUE THREAD

**Issue by benlk** [wp-cli/shell-command#22]
In [the documentation on WordPress.org](https://developer.wordpress.org/cli/commands/shell/), the flag `--basic` is described as follows:

> [--basic]
> Start in fail-safe mode, even if Boris is available.

What is Boris?

**Comment by gnanet** [comment]
Quick search on google reveals this :
https://github.com/wp-cli/wp-cli/pull/437

So [Boris](https://github.com/borisrepl/boris) is "A tiny REPL for PHP"

**Comment by schlessera** [comment]
Haha, that definitely needs a documentation improvement.

`wp shell` can use three different REPL imlpementations: https://github.com/wp-cli/shell-command/blob/v1.0.5/src/Shell_Command.php#L28-L30

The `--basic` flag forces the use of the built-in one, even if a better third-party option like Boris or PsySh is available.
