### ISSUE TITLE
PHP Parse Error on namespace

### ISSUE THREAD

**Issue by dustinpaluch** [wp-cli/shell-command#30]
```
wp> namespace dustinpaluch { }
PHP Parse error:  syntax error, unexpected 'dustinpaluch' (T_STRING), expecting \\ (T_NS_SEPARATOR) in phar:///usr/local/bin/wp/vendor/wp-cli/shell-command/src/WP_CLI/REPL.php(37) : eval()'d code on line 1
```

I'm trying to reproduce a bug involving namespaces, wp actions, and anonymous functions, and was hoping I'd be able to use the wp shell to make a minimal test case.

**Comment by schlessera** [comment]
The default REPL uses PHP `eval()` to execute the code, and `eval()` does not work properly with namespaces, a limitation in PHP itself.

If you want to use namespaces in `wp shell`, you install the additional `PsySH` REPL, which provides many improvements, one of them being support for namespaces.

One easy way to do so is through the package manager:
```
wp package install schlessera/wp-cli-psysh
```

**Comment by dustinpaluch** [comment]
Shouldn't this fail then?
```
php > eval('namespace dustinpaluch { function foobar() { echo __FUNCTION__; } foobar(); }');
dustinpaluch\foobar
```
