### ISSUE TITLE
Path to REPL.php is displayed for any wp shell command

### ISSUE THREAD

**Issue by GaryJones** [wp-cli/shell-command#45]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When doing any command in `wp shell` when SSH'd into a remote server, I get a path to the WP-CLI REPL file returned to me before the correct output.

**Describe how other contributors can replicate this bug**

```sh
wp> wp_revisions_to_keep( get_post( 3451690 ) );
=> phar:///root/roles/docker-container-web/usr/local/bin/wp/vendor/wp-cli/shell-command/src/WP_CLI/Shell/REPL.php:52:
int(50)
```

**Describe what you would expect as the correct outcome**

That this path should not appear when using the simplistic REPL.

```sh
wp> wp_revisions_to_keep( get_post( 3451690 ) );
int(50)
```

**Let us know what environment you are running this on**

```
OS:	Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64
Shell:	/bin/bash
PHP binary:	/root/roles/nginx-php/usr/local/php7.3/bin.stretch/php
PHP version:	7.3.16
php.ini used:	/usr/local/php7.3/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/vipdev
WP-CLI packages dir:	/home/{redacted}/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Provide a possible solution**

Maybe remove or fix [this `var_dump()`](https://github.com/wp-cli/shell-command/blob/56f0ff1bc36f6da2fb73cb932214adcde58270d8/src/WP_CLI/Shell/REPL.php#L52)?

**Comment by eduwass** [comment]
@GaryJones I know this is outdated but this happens to me to. 

@schlessera curious to know if that var_dump is in there for a particular reason?

**Comment by danielbachhuber** [comment]
> curious to know if that var_dump is in there for a particular reason?

Here's where it was added: https://github.com/wp-cli/shell-command/commit/4a7f30a36482d4ef2b034ab14bc4eda61b905974

It seems like it was intentional.

I can't get the behavior to reproduce in my shell, though... is there some clear way to reproduce?

**Comment by eduwass** [comment]
> > curious to know if that var_dump is in there for a particular reason?
> 
> Here's where it was added: [4a7f30a](https://github.com/wp-cli/shell-command/commit/4a7f30a36482d4ef2b034ab14bc4eda61b905974)
> 
> It seems like it was intentional.
> 
> I can't get the behavior to reproduce in my shell, though... is there some clear way to reproduce?

I'm not really sure, posted this a while ago, I tried to reproduce it now without success.

**Comment by danielbachhuber** [comment]
@GaryJones Any ideas on how to reproduce?

**Comment by GaryJones** [comment]
I can't recreate this now (even with schlessera/wp-cli-psysh package uninstalled, which is what I have usually now).
